// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Activity struct {
	ID          int32
	Title       string
	Description sql.NullString
	Type        string
	Status      string
	DueDate     sql.NullTime
	ContactID   int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Company struct {
	ID             int32
	Name           string
	Industry       sql.NullString
	Website        sql.NullString
	Phone          sql.NullString
	Email          sql.NullString
	Address        sql.NullString
	City           sql.NullString
	State          sql.NullString
	Country        sql.NullString
	Zipcode        sql.NullString
	CreatedBy      sql.NullInt32
	OrganizationID sql.NullInt32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Contact struct {
	ID                  int32
	ContactType         string
	FirstName           sql.NullString
	LastName            sql.NullString
	CompanyName         sql.NullString
	CompanyID           sql.NullInt32
	Email               string
	Phone               sql.NullString
	Address             sql.NullString
	City                sql.NullString
	State               sql.NullString
	Country             sql.NullString
	Zipcode             sql.NullString
	Position            sql.NullString
	SocialMediaProfiles sql.NullString
	Notes               sql.NullString
	TaxationDetailID    sql.NullInt32
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type Lead struct {
	ID             int32
	FirstName      string
	LastName       string
	Email          string
	Phone          sql.NullString
	Status         string
	AssignedTo     sql.NullInt32
	OrganizationID sql.NullInt32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Opportunity struct {
	ID          int32
	Name        sql.NullString
	Description sql.NullString
	Stage       sql.NullString
	Amount      sql.NullString
	CloseDate   sql.NullTime
	Probability sql.NullString
	LeadID      sql.NullInt32
	AccountID   sql.NullInt32
	OwnerID     sql.NullInt32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Task struct {
	ID          int32
	Title       string
	Description sql.NullString
	Status      string
	Priority    string
	DueDate     sql.NullTime
	ActivityID  int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type TaxationDetail struct {
	ID          int32
	Country     string
	TaxType     string
	Rate        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
